// ERRORS
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// USERS TYPES
export const SET_ERRORS = 'SET_ERRORS'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

// PORTFOLIOS TYPES
export const SET_PORTFOLIO = 'SET_PORTFOLIO'
export const SET_PORTFOLIOS = 'SET_PORTFOLIOS'
export const PORTFOLIO_LOADING = 'PORTFOLIO_LOADING'
export const PORTFOLIO_NOT_FOUND = 'PORTFOLIO_NOT_FOUND'
export const CLEAR_CURRENT_PORTFOLIO = 'CLEAR_CURRENT_PORTFOLIO'
